---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "https://raw.githubusercontent.com/konflux-ci/build-definitions/refs/heads/main/pipelines/docker-build-oci-ta/docker-build-oci-ta.yaml"
patches:
  - path: patch.yaml
    target:
      kind: Pipeline
