---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "https://raw.githubusercontent.com/konflux-ci/release-service-catalog/refs/heads/development/pipelines/managed/push-to-external-registry/push-to-external-registry.yaml"
patches:
  - path: patch.yaml
    target:
      kind: Pipeline
