---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  name: foreman-mcp-server-develop-nightly
  namespace: theforeman-org-tenant
  labels:
    release.appstudio.openshift.io/auto-release: "true"
spec:
  application: foreman-mcp-server
  target: foreman-mcp-server-nightly
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: foreman-mcp-server-nightly
  namespace: theforeman-org-tenant
spec:
  applications:
    - foreman-mcp-server
  origin: theforeman-org-tenant
  policy: foreman-mcp-server-release-policy
  pipeline:
    pipelineRef:
      resolver: git
      params:
        - name: url
          value: https://github.com/konflux-ci/release-service-catalog.git
        - name: revision
          value: production
        - name: pathInRepo
          value: pipelines/managed/push-to-external-registry/push-to-external-registry.yaml
    serviceAccountName: release-service-account
  data:
    mapping:
      components:
        - name: foreman-mcp-server-develop
          repository: quay.io/theforeman/foreman-mcp-server
          tags:
            - nightly
