---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "https://raw.githubusercontent.com/konflux-ci/build-definitions/refs/heads/main/task/buildah-oci-ta/0.9/buildah-oci-ta.yaml"
patches:
  - path: patch.yaml
    target:
      kind: Task
